### ISSUE TITLE
alipush plugin: init cloudchannel failed -- errorcode:10102

### ISSUE THREAD

**Issue by kunanfo** [llwwbb/cordova-plugin-AliPush#2]
alipush plugin: init cloudchannel failed -- errorcode:10102

接入时报以上错误问提，据阿里云官方解释，10102问题是包名与applicationId不一致造成的。以下是引用：

1 问题

推送SDK初始化时报如下错误：
init cloudchannel failerr:10102 - message:参数无效
2 问题原因

出现上述问题的原因是您在控制台配置的APP PackageName与您的工程中的ApplicationID不一致导致的。
3 解决方案

请查看工程build.gradle中applicationId设置情况，确保与控制台的PackageName保持一致。推送初始化错误且有错误码返回时可以参考：错误码列表

该如何配置并解决？

**Comment by llwwbb** [comment]
请确认你的AppKey和AppSecret，阿里云上配置的PackageName跟你实际的包名一致
